
    $CHANNEL_NAME:
        Consortium: $CONSORTIUM
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations: $CHANNEL_ORGS
            Capabilities:
                <<: *ApplicationCapabilities
