version: '2'

volumes:
  orderer0.edg:
  orderer1.edg:
  orderer0.crl:
  orderer1.crl:
  peer0.edgs:
  peer1.edgs:
  peer2.edgs:
  peer0.2:
  peer1.2:

networks:
  ihx:

services:

  orderer0.edg:
    container_name: orderer0.edg
    extends:
      file:  base/docker-compose-base.yaml
      service: orderer0.edg
    networks:
      - ihx

  orderer1.edg:
    container_name: orderer1.edg
    extends:
      file:  base/docker-compose-base.yaml
      service: orderer1.edg
    networks:
      - ihx

  orderer0.crl:
    container_name: orderer0.crl
    extends:
      file:  base/docker-compose-base.yaml
      service: orderer0.crl
    networks:
      - ihx

  orderer1.crl:
    container_name: orderer1.crl
    extends:
      file:  base/docker-compose-base.yaml
      service: orderer1.crl
    networks:
      - ihx

  peer0.edgs:
    container_name: peer0.edgs
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.edgs
    networks:
      - ihx

  peer1.edgs:
    container_name: peer1.edgs
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.edgs
    networks:
      - ihx

  peer2.edgs:
    container_name: peer2.edgs
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.edgs
    networks:
      - ihx

  peer0.2:
    container_name: peer0.2
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.2
    networks:
      - ihx

  peer1.2:
    container_name: peer1.2
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.2
    networks:
      - ihx

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.edgs:8050
      - CORE_PEER_LOCALMSPID=edges
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/edgs/peers/peer0.edgs/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/edgs/peers/peer0.edgs/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/edgs/peers/peer0.edgs/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/edgs/users/Admin@edgs/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - ihx
    depends_on:
      - orderer0.edg
      - orderer1.edg
      - orderer0.crl
      - orderer1.crl
      - peer0.edgs
      - peer1.edgs
      - peer2.edgs
      - peer0.2
      - peer1.2
